runtime: python27
api_version: 1
threadsafe: true
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 4
  min_idle_instances: 0
  max_idle_instances: 1
  target_cpu_utilization: .9
  target_throughput_utilization: .8
  min_pending_latency: 2000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80


libraries:
- name: webapp2
  version: "latest" 
- name: enum 
  version: "latest"
- name: yaml
  version: "latest"

handlers:
- url: /sprites
  static_dir: sprites
  application_readable: true

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /map
  static_dir: map
  application_readable: true

- url: /static
  static_dir: map/build/static
  application_readable: true

- url: /netcode/.*
  script: main.app

- url: /.*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?map/node_modules/.*$
- ^(.*/)?map/src/.*$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.bak$