runtime: python27
api_version: 1
threadsafe: true
instance_class: F2
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 900ms
  max_pending_latency: 1500ms
  max_concurrent_requests: 80


libraries:
- name: webapp2
  version: "latest" 

handlers:
- url: /sprites
  static_dir: sprites
  application_readable: true

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /map
  static_dir: map
  application_readable: true

- url: /static
  static_dir: map/build/static
  application_readable: true



- url: /.*
  script: main.app

skip_files:
- ^(.*/)?map/node_modules/.*$
- ^(.*/)?map/src/.*$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.bak$