runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /map
  static_dir: map
  application_readable: true

- url: /static
  static_dir: map/build/static
  application_readable: true

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?map/node_modules/.*$
- ^(.*/)?map/src/.*$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.bak$